### ISSUE TITLE
Support .Net Standard

### ISSUE THREAD

**Issue by LokiMidgard** [lennykean/WcfCoreMtomEncoder#1]
From the dependencys it seems it would alos work on .NetStandard. This would alows consuming this from .NetStandard libs.

**Comment by lscorcia** [comment]
Unfortunately it's not enough: this call is not available on .net standard:

https://github.com/lennykean/WcfCoreMtomEncoder/blob/85ee2145131ccb64371e500652479eaedfaeb2f6/src/WcfCoreMtomEncoder/MtomMessageEncoder.cs#L91

I wish it was... we have dozens of ancient MTOM web services to support!

**Comment by LokiMidgard** [comment]
@lscorcia are you shure? I changed `TargetFramework` to `netstandard2.0` and it worked. No compilation error, no RuntimeError.

And I'm sure that line was called. I had to migate a bug because the server I implement against has a trailing `;` in `Content-Type`. The HTTP spec does not allow that, and so `Content-Type` wasn't set correctly and needed to be fixed.

**Comment by LokiMidgard** [comment]
I just loocked where the method is defined. It is in the `microsoft.aspnet.webapi.client` package.

**Comment by lscorcia** [comment]
Hey, you are right! I was missing the reference to the package, thanks for mentioning it!
Now I just have to find how to send custom http headers in requests but that should be doable with a custom message inspector... thank you so much!!
