### ISSUE TITLE
MtomEnabledServiceClient

### ISSUE THREAD

**Issue by UREURE** [lennykean/WcfCoreMtomEncoder#4]
Where is defined "MtomEnabledServiceClient" from the example?

**Comment by LokiMidgard** [comment]
I know it's late, but I think thats the generated WCF client that extends `System.ServiceModel.ClientBase<TChanel>`

**Comment by lennykean** [comment]
@LokiMidgard is correct. That class name is really just a placeholder for whatever your specific service client is.
