### ISSUE TITLE
Client service missmatch

### ISSUE THREAD

**Issue by bobbyconnolly** [lennykean/WcfCoreMtomEncoder#9]
Hey there, thanks for the MtomEncoder

I'm getting
> System.Private.CoreLib: Exception while executing function: GenerateId. System.Private.ServiceModel: Content Type application/soap+xml; charset=utf-8 was not supported by service _--removed--_.  The client and service bindings may be mismatched.

here is my code
```cs
var encoding = new MtomMessageEncoderBindingElement(new System.ServiceModel.Channels.TextMessageEncodingBindingElement());

var transport = new System.ServiceModel.Channels.HttpsTransportBindingElement();
transport.AllowCookies = true;
transport.AuthenticationScheme = System.Net.AuthenticationSchemes.Basic;

var customBinding = new System.ServiceModel.Channels.CustomBinding(encoding, transport)
{
    Name = "BindingAuthBasicMtom",
    OpenTimeout = TimeSpan.FromMinutes(1),
    CloseTimeout = TimeSpan.FromMinutes(1),
    SendTimeout = TimeSpan.FromMinutes(10),
    ReceiveTimeout = TimeSpan.FromMinutes(10),
};

return customBinding;
```
The service requires ClientCredentialType = HttpClientCredentialType.Basic and uses BasicHttpBinding

Note: I changed `HttpTransportBindingElement` to `HttpsTransportBindingElement`

Any ideas?

**Comment by bobbyconnolly** [comment]
Maybe there's a way to do it with `CustBasicHttpBinding : BasicHttpBinding`

Basically, in .net Framework 2.0+ you have MessageEncoding (text, mtom) in this class. But on .net standard we don't 😨

**Comment by LokiMidgard** [comment]
Not sure if that could be the problem. But I have set the MessageVersion explicitly on `MtomMessageEncoderBindingElement`

```c#
// input:
// webservicePath - The URL
// userName - The user name
// password - The user password

var uri = new Uri(webservicePath);

var ea = new EndpointAddress(uri);

bool isSsl;
if (uri.Scheme == Uri.UriSchemeHttp)
    isSsl = false;
else if (uri.Scheme == Uri.UriSchemeHttps)
    isSsl = true;
else
    throw new NotSupportedException();

HttpTransportBindingElement transport;
if (isSsl)
    transport = new HttpsTransportBindingElement();
else
    transport = new HttpTransportBindingElement();

var encoding = new MtomMessageEncoderBindingElement(new TextMessageEncodingBindingElement())
{
    MessageVersion = MessageVersion.Soap11
};
var binding = new CustomBinding(encoding, transport);
transport.MaxReceivedMessageSize = int.MaxValue;
transport.MaxBufferSize = int.MaxValue;
            

transport.AuthenticationScheme = AuthenticationSchemes.Basic;

var client = new MyService(binding, ea);
            
client.ClientCredentials.UserName.UserName = userName;
client.ClientCredentials.UserName.Password = password;
client.Endpoint.EndpointBehaviors.Add(new BasicEndpointBehavior(basic));
return client;
```

**Comment by bobbyconnolly** [comment]
Thank you for your reply. I'll play with it a bit more perhaps later this month. I ended up targeting .net Framework instead of standard :(

**Comment by tinonetic** [comment]
> Not sure if that could be the problem. But I have set the MessageVersion explicitly on `MtomMessageEncoderBindingElement`
> 
> ```cs
> // input:
> // webservicePath - The URL
> // userName - The user name
> // password - The user password
> 
> var uri = new Uri(webservicePath);
> 
> var ea = new EndpointAddress(uri);
> 
> bool isSsl;
> if (uri.Scheme == Uri.UriSchemeHttp)
>     isSsl = false;
> else if (uri.Scheme == Uri.UriSchemeHttps)
>     isSsl = true;
> else
>     throw new NotSupportedException();
> 
> HttpTransportBindingElement transport;
> if (isSsl)
>     transport = new HttpsTransportBindingElement();
> else
>     transport = new HttpTransportBindingElement();
> 
> var encoding = new MtomMessageEncoderBindingElement(new TextMessageEncodingBindingElement())
> {
>     MessageVersion = MessageVersion.Soap11
> };
> var binding = new CustomBinding(encoding, transport);
> transport.MaxReceivedMessageSize = int.MaxValue;
> transport.MaxBufferSize = int.MaxValue;
>             
> 
> transport.AuthenticationScheme = AuthenticationSchemes.Basic;
> 
> var client = new MyService(binding, ea); // <----------------- HERE
>             
> client.ClientCredentials.UserName.UserName = userName;
> client.ClientCredentials.UserName.Password = password;
> client.Endpoint.EndpointBehaviors.Add(new BasicEndpointBehavior(basic)); // <---------------- and HERE
> return client;
> ```

Hi @LokiMidgard , I'm trying to understand the code. What is `MyService`? Is this a generated class? If so, how is it generated?

Also what package has `BasicEndpointBehavior`?

Thanks in advance!

**Comment by LokiMidgard** [comment]
@tinonetic `MyService` should be the generated service. It's some time since I posted the snippet.

`BasicEndPointBehaviour` is an implementation of `IEndpointBehavior` that is a custom implementation. I missed that...

```c#
 internal class BasicEndpointBehavior : IEndpointBehavior
    {
        private readonly BasicCredentials credentials;

        public BasicEndpointBehavior(BasicCredentials credentials)
        {
            this.credentials = credentials;
        }

        public void AddBindingParameters(ServiceEndpoint endpoint, BindingParameterCollection bindingParameters)
        {

        }
        public void ApplyClientBehavior(ServiceEndpoint endpoint, ClientRuntime clientRuntime)
        {
            clientRuntime.ClientMessageInspectors.Add(new Inspector(this.credentials));
        }
        public void ApplyDispatchBehavior(ServiceEndpoint endpoint, EndpointDispatcher endpointDispatcher) { }
        public void Validate(ServiceEndpoint endpoint) { }


        internal class Inspector : IClientMessageInspector
        {
            private readonly BasicCredentials credentials;

            public Inspector(BasicCredentials credentials)
            {
                this.credentials = credentials;
            }

            public void AfterReceiveReply(ref Message reply, object correlationState)
            {
            }

            public object? BeforeSendRequest(ref Message request, IClientChannel channel)
            {
                var target = channel.RemoteAddress.Uri;

                var property = request.Properties.ContainsKey(HttpRequestMessageProperty.Name)
                    ? (HttpRequestMessageProperty)request.Properties[HttpRequestMessageProperty.Name] 
                    : new HttpRequestMessageProperty();

              var header = "Basic " +
                             Convert.ToBase64String(System.Text.Encoding.ASCII.GetBytes($"{this.credentials.UserName}:{this.credentials.Password}"));
                property.Headers[HttpRequestHeader.Authorization] = header;
                if (!request.Properties.ContainsKey(HttpRequestMessageProperty.Name))
                    request.Properties.Add(HttpRequestMessageProperty.Name, property);

                return null;
            }
        }
    }
````
